### ISSUE TITLE
Could we use this cedatorma / recpd R package in microbiome studies?

### ISSUE THREAD

**Issue by emankhalaf** [cedatorma/recpd#1]
@cedatorma 
Hi,
I came across Plos publication to this new package but I can not see a clear tutorial online and I am wondering if this package could be used on phylogenetic trees generated from the microbiomes.  
I am currently working on different ecosystems and I found that some genera showed higher speciation (such as Pseudomonas) compared to other co-existent taxa. I know that the genus Pseudomonas is the most diverse bacterial genus, probably because it has a low recombination rate as mentioned in some publications, however, I am wondering whether this diversity is real or originated from the sequencer, or relevant to the ecosystem.
Thanks in advance for any suggestion in this regard
Eman

**Comment by cedatorma** [comment]
Hello @emankhalaf,

I've uploaded a tutorial, called RecPD-Tutorial.html in the ./vignettes/ folder. For some reason it wasn't uploaded. Thanks for bringing it to my attention.

RecPD is conceived for addressing whether features (phenotypes, gene-families, variants) have undergone recombination across a set of bacterial genomes, provided you have a already constructed reliable phylogenetic tree for them. It can be used for microbiome data, but I am not exactly sure how RecPD could be applied to address your question in checking whether or not the phylogenetic tree itself is reliable.

What would depend on the kind of sequencing are you dealing with, and what kind of data is going into the phylogenetic tree you've constructed? Is it metagenomics or 16S marker gene survey data? If you have metagenomics assemblies, the best approach I could suggest is to check for possible contamination in your genome assemblies using CheckM, and also check for recombination using ClonalFrameML. As far as controlling for any errors which might be introduced by sequencing itself, you could perform quality checks for your reads with fastqc, then use a tool like trimmomatic or fastp to make sure low-quality regions in your reads are filtered out. 

I hope this helps.

CB-T
